version: "3.8"

services:
  prodapp:
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: production
    image: projektinator-prod
    container_name: projektinator-prod
    depends_on:
      - proddb
    ports:
      - 5000:5000
    env_file:
      - ./.env
    volumes:
      - ./:/projektinator

  proddb:
    image: postgres:latest
    container_name: projektinator-prod-db
    volumes:
      - postgres-data:/var/lib/postgresql/data/
      - ./database_structure.sql:/docker-entrypoint-initdb.d/database_structure.sql
    env_file:
      - ./.env

volumes:
  postgres-data: null
