version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: dev
    image: projektinator-dev
    container_name: projektinator-dev
    env_file:
      - ./.env
    depends_on:
      - db
    ports:
      - 5000:5000
    volumes:
      - ./:/projektinator

  db:
    image: postgres:latest
    container_name: projektinator-db
    volumes:
      - postgres-data:/var/lib/postgresql/data/
      - ./database_structure.sql:/docker-entrypoint-initdb.d/database_structure.sql
    env_file:
      - ./.env

volumes:
  postgres-data: null
