version: "3.8"

services:
  testapp:
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: test
    image: projektinator-test-dev
    container_name: projektinator-test-dev
    depends_on:
      - testdb
    ports:
      - 5005:5000
    environment:
      - SECRET=test
      - DATABASE_URI=postgresql://test:test@projektinator-test-db:5432/projektinator-test
    volumes:
      - ./:/projektinator

  testdb:
    image: postgres:latest
    container_name: projektinator-test-db
    environment:
      - POSTGRES_USER=test
      - POSTGRES_DB=projektinator-test
      - POSTGRES_PASSWORD=test
      - POSTGRES_PORT=5432
    volumes:
      - ./database_structure.sql:/docker-entrypoint-initdb.d/02-database_structure.sql
