class User:
    """Class User resembles user as a object from the database.
    """

    def __init__(self, uid: str, username: str, user_role: int, password_hash: str, firstname: str, lastname: str, email: str, profile_image: str):
        """Initializes User object with given values

        Args:
            uid (str): holds user's id in database, needs to be unique, is in uuid4 format generated by database
            username (str): username is unique, required string that hold's user's username
            user_role (int): tells user's rights in system
            password_hash (str): holds user's password in encrypted format
            firstname (str): holds user's firstname
            lastname (str): holds user's lastname
            email (str): holds user's email
            profile_image (str): holds user's profile image as base64 encoded string or default value
        """
        self.uid = uid
        self.username = username
        self.user_role = user_role
        self.password_hash = password_hash
        self.firstname = firstname
        self.lastname = lastname
        self.email = email
        self.profile_image = profile_image
