from utils.helpers import fullname


class User:
    """Class User resembles user as a object from the database.
    """

    def __init__(self, uid: str, username: str, user_role: int,
                 user_role_name: str, password_hash: str, firstname: str,
                 lastname: str, email: str, profile_image: str, teid: str,
                 tename: str):
        """Initializes User object with given values

        Args:
            uid (str): holds user's id in database, needs to be unique, is in uuid4 format generated by database
            username (str): username is unique, required string that hold's user's username
            user_role (int): tells user's rights in system
            password_hash (str): holds user's password in encrypted format
            firstname (str): holds user's firstname
            lastname (str): holds user's lastname
            email (str): holds user's email
            profile_image (str): holds user's profile image as base64 encoded string or default value
        """
        self.user_id = uid
        self.username = username
        self.user_role = user_role
        self.user_role_name = user_role_name
        self.password_hash = password_hash
        self.firstname = firstname
        self.lastname = lastname
        self.fullname = fullname(self.firstname, self.lastname)
        self.email = email
        self.profile_image = profile_image
        self.team_id = teid
        self.team_name = tename

    def __str__(self) -> str:
        """Method for generating formatted string from object to be mainly used in debugging matters.

        Returns:
            str: user object in formatted string
        """

        pw_hash_ok = True if self.password_hash[:len(
            "pbkdf2:sha256:260000$")] == "pbkdf2:sha256:260000$" else False

        return (f'User ”{self.fullname} ({self.username})”\n'
                f' - id ”{self.user_id}”\n'
                f' - firstname ”{self.firstname}”\n'
                f' - lastname ”{self.lastname}”\n'
                f" - user's role ”{self.user_role_name}”\n"
                f' - password_hash ok ”{pw_hash_ok}”\n'
                f' - email ”{self.email}”\n'
                f' - team ”{self.team_name}”\n'
                f' - profile image ”{self.profile_image}”\n')
